### ISSUE TITLE
SA-BERT source code

### ISSUE THREAD

**Issue by hrdxwandg** [JasonForJoy/Leaderboards-for-Multi-Turn-Response-Selection#1]
hi, can you share the SA-BERT model source code?

**Comment by JasonForJoy** [comment]
@hrdxwandg 
Our work on SA-BERT is under peer review now.
We will release the code after paper acceptance soon. 
Please keep an eye on our work if you are interested. Thanks.

**Comment by hrdxwandg** [comment]
@JasonForJoy 
thanks your reply
in your paper, I am confused about the section **Speaker-Aware Disentanglement Strategy**  I feel it is a heuristic method。but I can not well understand. I hava real electronic commerce chat data with customer and seller. How can I use your method to refine my data?

**Comment by JasonForJoy** [comment]
@hrdxwandg 
In the dataset used in our paper, there are multiple speakers, which we name them S1, S2, S3, ...
In this disentanglement strategy, we select only a small number of utterances which are relevant to a specific speaker.
You can select some utterances which are relevant to a specific customer or seller in your setting.

**Comment by hrdxwandg** [comment]
@JasonForJoy 
ok. it's some different with my data. within a session in my data. there only two speaker, S1, S2.the customer and seller
but the order maybe S1, S2, S2, S1, S1, S2, S1, S2

In this situation. the disentanglement strategy is not necessary.

**Comment by hrdxwandg** [comment]
@JasonForJoy  thanks for your explanation
